# AutoPwnGPT Configuration

# Application settings
application:
  name: "AutoPwnGPT"
  version: "0.1.0"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_directory: "data/logs"
  temp_directory: "data/temp"
  session_directory: "data/sessions"
  reports_directory: "data/reports"
  payloads_directory: "data/payloads"
  wordlists_directory: "data/wordlists"

# Security settings
security:
  scope_enforcement: true
  target_whitelist: []  # List of allowed targets (domains, IPs)
  target_blacklist: []  # List of forbidden targets
  max_concurrent_tasks: 5
  max_scan_duration: 3600  # seconds
  watermark: true
  audit_logging: true

# LLM settings
llm:
  provider: "openai"  # openai, local
  api_key: ""  # Will be overridden by environment variable OPENAI_API_KEY
  model: "gpt-4-0125-preview"  # or local model name
  temperature: 0.1
  max_tokens: 4096
  local_model_path: ""
  prompt_templates_directory: "data/templates/prompts"
  
  # Local LLM settings (used when provider is "local")
  local:
    host: "localhost"
    port: 11434
    model: "llama3"

# Database settings
database:
  type: "sqlite"  # sqlite, postgresql, mysql
  path: "data/autopwngpt.db"  # for sqlite
  host: ""  # for postgresql/mysql
  port: ""  # for postgresql/mysql
  name: ""  # for postgresql/mysql
  user: ""  # for postgresql/mysql
  password: ""  # for postgresql/mysql

# Module settings
modules:
  enabled_modules:
    - "scanners"
    - "exploits"
    - "enumeration"
    - "brute_force"
    - "post_exploitation"
  scan_timeout: 300  # seconds
  exploit_timeout: 120  # seconds
  module_directories:
    - "src/modules"
    - "src/modules/custom"
  
# GUI settings
gui:
  theme: "dark"  # dark, light
  font_family: "Roboto"
  font_size: 11
  auto_save_session: true
  session_save_interval: 300  # seconds

# CLI settings
cli:
  prompt_style: "autopwngpt> "
  enable_autocomplete: true
  history_file: ".autopwngpt_history"
  
# API settings
api:
  enabled: false
  host: "127.0.0.1"
  port: 8080
  debug: false
  authentication: true
  jwt_secret: ""  # Will be auto-generated if empty
  rate_limit: 100  # requests per minute

# Tool integrations
integrations:
  nmap:
    path: "nmap"  # system path or custom path
    args: "-sV -sC"
  metasploit:
    path: "msfconsole"
  sqlmap:
    path: "sqlmap"
  burpsuite:
    path: ""  # Leave empty to disable
  hydra:
    path: "hydra"
