name: Security Vulnerability
description: Report a security vulnerability in AutoPwnGPT
title: "[SECURITY] "
labels: ["security"]
assignees: []
body:
  - type: markdown
    attributes:
      value: "**IMPORTANT**: For critical security vulnerabilities, please report them confidentially to [security contact email] instead of creating a public issue."

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: A clear and concise description of the security vulnerability.
    validations:
      required: true

  - type: input
    id: component
    attributes:
      label: Affected Component
      description: Which component is affected by this vulnerability?
      placeholder: "e.g., Authentication, Module System, API"
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of AutoPwnGPT are you running?
      placeholder: "e.g., 1.0.0"
    validations:
      required: true

  - type: input
    id: module
    attributes:
      label: Module (if applicable)
      description: If this affects a specific module, please specify
      placeholder: "e.g., network_scanner"

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the vulnerability
      placeholder: |
        1. Configure '...'
        2. Run command '...'
        3. Execute '...'
        4. Observe vulnerability
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Describe the potential impact of this vulnerability if exploited.
    validations:
      required: true

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Fix/Mitigation
      description: If you have suggestions for addressing the vulnerability, describe them here.

  - type: checkboxes
    id: verification
    attributes:
      label: Additional Information
      options:
        - label: I have tested this on the latest version
          required: true
        - label: I have checked for similar reports
          required: true
        - label: I understand this will be kept private until mitigated
          required: true